spring.application.name=pedidos360-bff

server.port=8080

pedidos360.security.issuer=https://sts.windows.net/bb5324af-c266-41ed-b36c-a971641c7af2/

pedidos360.security.audience=api://770fe373-4625-41b9-831c-50a3d7fd4274

pedidos360.security.jwk-set-uri=https://login.microsoftonline.com/bb5324af-c266-41ed-b36c-a971641c7af2/discovery/keys