spring.application.name=pedidos360-bff

server.port=8080

# Microsoft Entra ID / JWT
pedidos360.security.issuer=https://sts.windows.net/bb5324af-c266-41ed-b36c-a971641c7af2/
pedidos360.security.audience=api://770fe373-4625-41b9-831c-50a3d7fd4274
pedidos360.security.jwk-set-uri=https://login.microsoftonline.com/bb5324af-c266-41ed-b36c-a971641c7af2/discovery/keys

# Amazon RDS MySQL
spring.datasource.url=jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:pedidos360}?sslMode=REQUIRED&serverTimezone=UTC
spring.datasource.username=${DB_USERNAME:adminpedidos}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.jpa.show-sql=false
